assetlist.schema.json
chain.schema.json
chains/initiation-1/chain.json
chains/minimove-1/chain.json
chains/miniwasm-1/chain.json

This PR adds a chain.schema.json file to define how each chain.json file should look. Right now, this is just a chain name and api (rest, rpc, grpc) endpoints.
This also adds initial initia chains that have skip authorized endpoints (initia, minimove, miniwasm).

[API-3174] Chain schema & Initia endpoints

---

chains/glados-1/chain.json
initia.chain.schema.json

- introduce `index_for_skip` for basic auth generation

add index_for_skip field

---

chains/glados-1/chain.json

- remove `temp` from endpoints

update milkyway endpoints urls

---

chains/1/chain.json

Reverts skip-mev/skip-go-registry#27

Revert "disable eth mainnet go fast since gas is too high"

---

chains/137/assetlist.json

- Switch MATIC to POL for Polygon, and also update the coingecko ID

Deprecate MATIC for POL

---

chain.schema.json
chains/1329/chain.json

Adds `pretty_name` to chain schema and also adds a `chain.json` entry for Sei EVM

Add pretty name to chains

---

assetlist.schema.json
chains/1/assetlist.json
chains/10/assetlist.json
chains/11155111/assetlist.json
chains/11155420/assetlist.json
chains/1284/assetlist.json
chains/1329/assetlist.json
chains/137/assetlist.json
chains/169/assetlist.json
chains/250/assetlist.json
chains/314/assetlist.json
chains/42161/assetlist.json
chains/421614/assetlist.json
chains/42220/assetlist.json
chains/43113/assetlist.json
chains/43114/assetlist.json
chains/56/assetlist.json
chains/59144/assetlist.json
chains/80002/assetlist.json
chains/81457/assetlist.json
chains/8453/assetlist.json
chains/84532/assetlist.json
chains/984122/assetlist.json
chains/984123/assetlist.json
chains/osmosis-1/assetlist.json
chains/pacific-1/assetlist.json

Reverts skip-mev/skip-go-registry#35

[API-3746] Assetlist schema required field updates

---

chains/culinaris-2/chain.json
chains/preyominet-1/chain.json
chains/zaar-testnet-1/chain.json

Add `preyominet-1` (kamigochi), `zaar-testnet-1` and `culinaris-2` chain.

feat: add yominet, zaar and culinaris testnet chain

---

chains/rehearsal-1/chain.json
chains/rehearsal-minievm-1/chain.json
chains/rehearsal-minimove-1/chain.json
chains/rehearsal-miniwasm-1/chain.json

Add 4 chains for rehearsal-1
- rehearsal-1
- rehearsal-minimove-1
- rehearsal-miniwasm-1
- rehearsal-minievm-1

feat: add rehearsal-1 chains

---

chains/culinaris-2/chain.json
chains/glados-2.1/chain.json
chains/initiation-2/chain.json
chains/landlord-2/chain.json
chains/minievm-2/chain.json
chains/minimove-2/chain.json
chains/miniwasm-2/chain.json
chains/preyominet-1/chain.json
chains/rehearsal-1/chain.json
chains/rehearsal-minievm-1/chain.json
chains/rehearsal-minimove-1/chain.json
chains/rehearsal-miniwasm-1/chain.json
chains/zaar-testnet-3/chain.json
initia.chain.schema.json

Extend initia chain schema with `is_initia_l1` and `initia_l1_chain_id` fields

initia chain schema update

---

chains/rave-test4/chain.json

feat: add rave-test4

---

chains/inertiation-10/chain.json
chains/infinityg-1/chain.json

feat: add infinityg chain

---

chains/echelon-testnet-1/chain.json
chains/zaar-testnet-4/chain.json

update echelon and zaar

---

chains/interwoven-1/chain.json

feat: add interwoven-1

---

chains/virgaze-1/chain.json

add intergaze testnet

---

chains/11155111/assetlist.json
chains/bbn-test-5/assetlist.json

Adds coingecko ids for various eureka assets and creates an assetlist for baby on babylon

update eureka asset info

---

chains/11155111/assetlist.json

add weth on sepolia

---

chains/yominet-1/chain.json

add yominet

---

chains/nuwa-rollup-1/chain.json

- add rena testnet on initiation-2

add rena testnet

---

chains/ingnetwork-1/chain.json
chains/moo-1/chain.json
chains/zaar-mainnet-1/chain.json

add initia mainnet rollups

---

chains/testbfb/chain.json

- Add testbfb-3 and remove culinaris-2

Add testbfb-3 and remove culinaris-2

---

chains/embrmainnet-1/chain.json

add embrmainnet

---

chains/landlord-3/chain.json

Adding the new testnet for Civitia (Initia Rollup)

Add new Civitia Testnet (landlord-3)

---

chains/embr-1/chain.json

update embr chain name

---

chains/interwoven-1/assetlist.json

Add proper metadata override for Celestia (TIA) token on interwoven-1

Add TIA metadata for interwoven-1
